  openapi: 3.1.0
  info:
    title: A minimal OpenAPI Description
    version: 0.0.1
  paths: 
    /Reservation:
      delete:
        summary: cancel a reservation
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  reservation_number:
                    type: integer
                  pin:
                    type: integer
                  required:
                    - reservation_number
                    - pin
        responses:
          "200": 
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
      post:
        summary: Reserve a table
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  tischnummer:
                    type: string
                  zeitpunkt:
                    type: string
                    format: date-time
                  required:
                    - tischnummer
                    - zeitpunkt
        responses:
          "200": 
            description: "OK"
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    pin:
                      type: integer
                    reservierungsnummer:
                      type: integer
                    storniert:
                      type: bool
                    tischnummer:
                      type: integer
                    zeitpunkt:
                      type: string
                      format: date-time
    /FreeTables:
      get:  
        summary: check if a table is free
        requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: string
                  format: date-time
                tableNr:
                  type: integer
                required:
                  - timestamp
        responses:
          "200": 
            description: "OK"
            content:
              application/json:
                schema:
                  type: array
                  items:
                    type: object
                    properties:
                      pin:
                        type: integer
                      reservierungsnummer:
                        type: integer
                      storniert:
                        type: bool
                      tischnummer:
                        type: integer
                      zeitpunkt:
                        type: string
                        format: date-time
